### ISSUE TITLE
[teslamate-chart] Error 426 upgrade required on kubernetes

### ISSUE THREAD

**Issue by MarcoStuurman** [billimek/billimek-charts#109]
Hi,

I'm trying to install the teslamate chart but I can't get the websockets to work. Is there any extra steps needed to make this work?

WebSocket connection to 'ws://tesla.xx.xxx/live/websocket?baseUrl=http%3A%2F%2Ftesla.xx.xxx&referrer=&vsn=2.0.0' failed: Error during WebSocket handshake: Unexpected response code: 426

I'm using the nginx ingress controller with no special changes and forwarding all paths, including /ws/ to port 4000 in the pod. I'm seeing the panel, but the websocket is giving errors.

Is there a special configuration needed in the NGINX ingress config? Or am I missing something else?

Thank you!

**Comment by billimek** [comment]
It's strange you're having this issue.  Are you deploying any other workloads that also use ingress with websockets?

My teslamate ingress configuration is really tame: source files are [here](https://github.com/billimek/k8s-gitops/blob/master/default/teslamate/teslamate.yaml) and [here](https://github.com/billimek/k8s-gitops/blob/master/default/teslamate/teslamate-helm-values.txt)

Here's a sanitized dump of the ingress object I use (I use an external oauth provider but that should only make things more difficult for websockets truth be told):

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    flux.weave.works/antecedent: default:helmrelease/teslamate
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-signin: https://auth.mydomain.com/oauth2/start
    nginx.ingress.kubernetes.io/auth-url: https://auth.mydomain.com/oauth2/auth
  creationTimestamp: "2019-12-22T06:32:55Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: teslamate
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: teslamate
    helm.sh/chart: teslamate-1.0.0
  name: teslamate
  namespace: default
  resourceVersion: "42310813"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/teslamate
  uid: 2282528b-f76f-44c9-87f0-28b1936c5ee4
spec:
  rules:
  - host: teslamate.mydomain.com
    http:
      paths:
      - backend:
          serviceName: teslamate
          servicePort: http
        path: /
  tls:
  - hosts:
    - teslamate.mydomain.com
status:
  loadBalancer:
    ingress:
    - {}
```

nginx-ingress configuration is [equally spartan](https://github.com/billimek/k8s-gitops/blob/master/kube-system/nginx/nginx.yaml)

**Comment by billimek** [comment]
Here's a screenshot of the devtools console interaction with my teslamate deployment in case that helps any:

![image](https://user-images.githubusercontent.com/6393612/71789049-3cfe9900-2ff6-11ea-8c67-4c7a8b1b07f2.png)

**Comment by MarcoStuurman** [comment]
I've had some things running. Mostly for testing purposes, so I've removed a lot. I noticed I had haproxy in front of nginx-ingress running, this caused the problem. I'm sorry to have bothered you. Thank you for this chart, it works great!
