### ISSUE TITLE
migrate helm/charts back to this repo?

### ISSUE THREAD

**Issue by billimek** [billimek/billimek-charts#110]
Given the [deprecation of the helm/charts stable repo](https://github.com/helm/charts#deprecation-timeline), it stands to reason that a new home should be found for some of the charts.

Charts I'm an owner (or co-owner) of right now in the `helm/charts` repo:

* `unifi`
* `home-assistant`
* `node-red`
* `minecraft`
* `nextcloud`

`unifi`, `home-assistant`, and `node-red` originated in this repo and it shouldn't be a big deal to move them back.  Will need to check with the other co-owners of the minecraft and nextcloud chart to see what they want to do.

**Comment by onedr0p** [comment]
The offical repo for helm/charts is going away? I wonder why they are doing this, there's no explanation as to why other than "because helm 3".

I can guess that maintaining such a large repo is a heavy lift for chart OWNERS and repository maintainers.

**Comment by billimek** [comment]
Some progress on this:

* **unfi**: Email sent to co-maintainer and [issue opened](https://github.com/jacobalberty/unifi-docker/issues/310) to see about hosting on the jacobalberty/unifi-docker repo.  Otherwise, we will bring it back here.
* **home-assistant**: Email sent to co-maintainer seeking opinions. I already reached out to the home-assistant folks and they have [no interest in doing anything with the helm chart](https://discordapp.com/channels/330944238910963714/554842238073700352/704699873848590406).  We will likely bring it back here once I hear back from co-maintainer.
* **node-red**: Already communicated with co-maintainer and we will bring the chart back here.
* **minecraft**: Email sent to co-maintainers and we will likely host it in a dedicated chart repo under @itzg's github space where the docker repos already live.
* **nextcloud**: Communication initiated with co-maintainer and [issue opened](https://github.com/nextcloud/docker/issues/1130) in the nextcloud docker repo seeking to use that place as a home.  If they don't want it there, we can host the chart here.

**Comment by billimek** [comment]
**node-red** chart is migrated to this repo with the merge of [this PR](https://github.com/helm/charts/pull/22739)

**Comment by billimek** [comment]
**home-assistant** chart is fully migrated to this repo with the merge of [this PR](https://github.com/helm/charts/pull/22745)

**Comment by billimek** [comment]
minecraft chart has a home with the minecraft docker image: https://github.com/itzg/minecraft-server-charts

**Comment by billimek** [comment]
**nextcloud** chart has a new home in the [nextcloud](https://github.com/nextcloud/) github org: https://github.com/nextcloud/helm

**Comment by billimek** [comment]
Will handle the remaining **unifi** chart in the [new home](https://github.com/k8s-at-home/charts)
