### ISSUE TITLE
Ombi 2.1.0 didn't get published

### ISSUE THREAD

**Issue by onedr0p** [billimek/billimek-charts#177]
Still shows latest as 2.0.3 here https://hub.helm.sh/charts/billimek/ombi

**Comment by billimek** [comment]
@onedr0p can you please check again?  GitHub wasn't 'publishing' from the `gh-pages` branch and gave a generic error about 'something went wrong, please try again later'.  I forced a rebuild and see the intended changes now.

**Comment by onedr0p** [comment]
Helm Hub still not showing the latest

**Comment by billimek** [comment]
Yeah, it appears that Helm Hub updates on some periodic basis and I've seen it take up to an hour for repo updates to reflect.  Can you wait a short while and check again?  It would be great if Helm Hub offered some way to webhook updates so we don't need to wait.

**Comment by billimek** [comment]
Hmm interesting.  It looks like when tautuli was updated, the automation [_removed_](https://github.com/billimek/billimek-charts/commit/31f42fef71d4426b7aa1c4988652d49cd829e695) the ombi update as well.  This is no good.

Looking into this now.

**Comment by billimek** [comment]
Ok, after forcing a new release and subsequent re-publishing, it showed-up on Helm Hub after ~60 mins.  Version 2.1.1:
![image](https://user-images.githubusercontent.com/6393612/76570470-bd74c680-648b-11ea-8b88-de75136bf4d5.png)
