### ISSUE TITLE
Migrate Metallb chart

### ISSUE THREAD

**Issue by onedr0p** [billimek/billimek-charts#195]
@billimek what do you think about migrating the Metallb chart to here, since the developers have no interest in maintaining one themselves?

**Comment by billimek** [comment]
This is a good idea.  I will work on hosting a metallb chart here given that the [official repo](https://github.com/metallb/metallb) currently has no interest in hosting a helm chart, the 'stable' helm charts repo is being deprecated, and there is no one maintaining the [stable/metallb chart](https://github.com/helm/charts/tree/master/stable/metallb) anyway.

Hopefully a better long-term solution will materialize, but for now we can have a solution for helm users wanting to use the MetalLB solution via helm.

**Comment by billimek** [comment]
It looks like bitnami picked-up hosting a metallb chart 🤔

https://github.com/bitnami/charts/tree/master/bitnami/metallb

**Comment by billimek** [comment]
They are making their own container images for metallb (amd64 only) instead of using the 'official' metallb docker containers (multi-arch) - that seems sort of sketchy.

**Comment by onedr0p** [comment]
They do that for a bunch of docker images, like redis. Not sure why they are doing it for metallb to be honest.

**Comment by onedr0p** [comment]
I've migrated over to their chart and docker image. Will let you know if I notice anything funky.

**Comment by onedr0p** [comment]
https://github.com/bitnami/bitnami-docker-metallb-speaker#why-use-bitnami-images

**Comment by onedr0p** [comment]
I am getting this error with their chart:

```
[helm-operator-7745bc4c9f-sw6js] ts=2020-06-02T14:33:43.703489511Z caller=release.go:273 component=release release=metallb targetNamespace=kube-system resource=kube-system:helmrelease/metallb helmVersion=v3 error="installation failed: Service \"metallb-speaker-metrics\" is invalid: metadata.labels: Invalid value: \"app.kubernetes.io/name\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')" phase=install
```

I have reverted for now.

**Comment by onedr0p** [comment]
I am going to close this because it looks like bitnami is doing it's best to support metallb.

https://github.com/bitnami/charts/tree/master/bitnami/metallb
