### ISSUE TITLE
Update README for Plex Chart

### ISSUE THREAD

**Issue by onedr0p** [billimek/billimek-charts#213]
Looks like we're missing the value keys and description for everything.

**Comment by runecalico** [comment]
Yep,  That is totally on me. I noticed the original readme wasn't up to date and then ignored it (lazy) when adding my updates. I DID at least put mostly useful comments in values.yaml :)

**Comment by billimek** [comment]
IMO it's a pain to keep the values table updated with the actual values file, and lately I've been creating charts with just a link to the `values.yaml` file (which should be properly commented) for details on what values that can be used.

**Comment by billimek** [comment]
Closing, lets re-open if we need to revisit this!
