### ISSUE TITLE
Radarr 4.0.0 release didn't seem to work

### ISSUE THREAD

**Issue by mterhar** [billimek/billimek-charts#230]
```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "nginx-stable" chart repository
...Successfully got an update from the "billimek" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
$ helm search repo billimek | grep radarr
billimek/radarr              	3.2.0        	v0.2.0.1480-ls58                                  	Radarr is a movie downloading client  
```

Looking at the gh-pages branch, the yaml still says 3.2.0 is the newest. 

The helm release action seems to have happened in the actions too. 

I already followed to docs to merge the download and movies mounts into one place so now I'm in limbo.  The next course of action is cloning this repo and using the charts directly.  Just wanted to see if there was some re-publishing mechanism or if I missed something.

**Comment by billimek** [comment]
This is really odd.  Commit https://github.com/billimek/billimek-charts/commit/e28bddada21d9e27d3ec5810d792aa38c2eb7ad2 shows that it was added, but when looking at the file on the branch, it's not there.

I'll dig into this and try to figure out what broke and why.

**Comment by billimek** [comment]
Ok, the lidarr release seemed to remove it in this commit: https://github.com/billimek/billimek-charts/commit/1ec6cab63854144ca0b178ec77d4c11f5393d9ee

I suspect there is an issue with the action(s) when they are run too close together.

**Comment by billimek** [comment]
Just created radarr release `4.0.1` via automation to get around the missing version.

I'm still exploring why this happened and how to prevent in the future.

**Comment by billimek** [comment]
https://github.com/helm/chart-releaser-action/issues/27 created for this, FYI

**Comment by billimek** [comment]
https://github.com/billimek/billimek-charts/pull/232 may fix this from happening in the future.
