### ISSUE TITLE
rtorrent-flood - How does the web ui connect to rtorrent?

### ISSUE THREAD

**Issue by windowsrefund** [billimek/billimek-charts#240]
When firing up the web interface, the user is presented with the "rTorrent Connection Type" dialog with TCP and Unix Socket options

What is the current expectation/assumption being made here in terms of workflow? 

Thanks in advance

**Comment by billimek** [comment]
Hi @windowsrefund, I believe you need to select "Unix Socket" as the connection type and use the value `/tmp/rtorrent.sock` as shown below:

![image](https://user-images.githubusercontent.com/6393612/84044118-24175c80-a975-11ea-8494-be9a8c52413d.png)

There is probably a better way to script or automate this but I haven't been able to figure it out yet.

**Comment by windowsrefund** [comment]
Thank you very much.
