### ISSUE TITLE
Plex hostNetwork option?

### ISSUE THREAD

**Issue by onedr0p** [billimek/billimek-charts#260]
I see with the HA chart we have this option, @billimek do you think we can add this to Plex chart too? It might solved the issue with local clients streaming with a clusterIP address.

**Comment by billimek** [comment]
It's probably a good idea, if nothing else to have the option!

**Comment by onedr0p** [comment]
I am still on the old chart, I am hesitant to migrate :P Your steps should be good to follow, I am just scared...

```
What I did was:

• scale my existing plex to 0
• backup the config pv
• deleted the existing plex helmrelease
• installed the new plex helmrelease
• scaled the new plex to 0
• restored the backup data
• scaled to 1
```

**Comment by onedr0p** [comment]
This was implemented, closing.
