### ISSUE TITLE
Broken ingress on all charts recently updated

### ISSUE THREAD

**Issue by onedr0p** [billimek/billimek-charts#309]
@w4 do you mind correcting these? The charts are now broken.

```
[helm-operator-55f6946fbc-6djtz] ts=2020-08-05T12:57:59.516970966Z caller=release.go:278 component=release release=tautulli targetNamespace=default resource=default:helmrelease/tautulli helmVersion=v3 error="installation failed: YAML parse error on tautulli/templates/ingress.yaml: error converting YAML to JSON: yaml: line 12: could not find expected ':'" phase=install
```

**Comment by w4** [comment]
Of course, apologies. To be honest I only tried this on Sonarr/Radarr and relied on the build system to test the rest.

Is this caused by the default value of `{}` or is something overriding it so it's empty?

**Comment by onedr0p** [comment]
Not sure but you should be able to mimic the annotations code blocks
