### ISSUE TITLE
New home for this repo

### ISSUE THREAD

**Issue by billimek** [billimek/billimek-charts#317]
Now that the [helm/charts repo](https://github.com/helm/charts/) is deprecated and this repo has grown beyond just personal charts, it makes sense to leverage a much better named place to host charts related to k8s at home.  @onedr0p, @carpenike, and myself have a [k8s-at-home github org](https://github.com/k8s-at-home) that seems like a logical fit for a new home for these charts.

~Therefore, we would like to 'transfer' this repo to [k8s-at-home](https://github.com/k8s-at-home) and rename it to 'charts'.  Github will automatically 'follow' the transfer and rename from the existing repo, so links should continue to work.~ Transfer approach would not work as expected. Will replicate to the new home instead.

At a high-level, the following will likely be necessary:

- [x] create new repo in https://github.com/k8s-at-home/charts
- [x] clone this repo to preserve git history and push directly as the new charts repo (https://github.com/k8s-at-home/charts)
- [x] freeze contributions from non-maintainers (in both repos)
- [x] Update github actions to reflect new home
- [x] Update gh-pages branch to reflect new home
- [x] Update main and chart READMEs to reflect new home
- [x] Ensure that https://k8s-at-home.com/charts/ points to the transferred repo
- [x] 'transfer' all open issues to new repo
- [x] Add the maintainers for group effort at updating all the different aspects on both repos
- [x] For each chart, create a PR in the old repo to depreacate and reference new home.  See #346 for an example
- [x] Once new repo is satisfactorily ready/updated merge above branch in old repo
- [x] Archive with established date on main readme saying it will be removed at x date
- [x] unfreeze contributions from non-maintainers (in new repo)

**Comment by Juggels** [comment]
Maybe this is also a good moment to think about adding support for [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners)? 

That way you could (for example) automatically assign additional pull request reviews to people you deem responsible for the contents of certain charts.

**Comment by billimek** [comment]
@Juggels this is an excellent idea, thank you!

**Comment by bjw-s** [comment]
As for the `CODEOWNERS `feature, it seems that currently [it's not possible to keep a `CODEOWNERS `file per chart](https://github.community/t/nested-codeowners/2976) 😞 That would mean having a single `CODEOWNERS `file in the repo root folder. It could work, but if the repo grows in terms of charts/PR's the chance of merge conflicts will definitely increase.

**Comment by carpenike** [comment]
Perhaps management of that file should only be handled by overall program administrators and PRs shouldn't be allowed to it?

**Comment by billimek** [comment]
Concern that while github will properly redirect a transferred & renamed repo (i.e. the old URLs continue to 'work'), the custom helm repo URL (https://billimek.com/billimek-charts/) will break.  Need to test this and see if there is a clean workaround.

Alternatively, an approach could be to stand up a completely separate & new repo over in `k8s-at-home/charts` and 'deprecate' these charts and update READMEs to direct folks over to the new location.  This is less ideal IMO because it will fracture the use and make it not obvious that charts have moved (maybe?).

**Comment by DirtyCajunRice** [comment]
@billimek Just to be clear, why will the above break? Instead of pointing it to a gh-pages directly just point it to a reverse-proxy somewhere and point it at the new location with a rewrite. Thoughts?

**Comment by DirtyCajunRice** [comment]
Actually... now that i think about it more... the deprecation may be the only way to be "graceful" about it. If the url is pointed to the new repo 
* users will effectively never have to stop using the url
* there will be no way to separate "new" versions of charts to not show up on the old url
* there would be no way to notify the user that there has even been a migration outside of hoping they check in (vs the deprecation method that lets them know on install/upgrade)

IMO:
* clone the repo to preserve git history and push directly as the new charts repo
* freeze contributions from non-maintainers
* Add the maintainers for group effort at updating all the different aspects on both repos
* create a branch in the old repo to stage full sweep deprecation in one MR
* Once new repo is satisfactorily ready/updated merge above branch in old repo

or something of that nature?

**Comment by carpenike** [comment]
Another option — why don’t we just keep the dns name as is and work out a migration plan to a new namespace after the migration is complete? We can do a reverse proxy for the k8s-at-home.com namespace and get that working, update all guides to point to new name, then after X period of time we change the DNS name on the repo itself?

**Comment by billimek** [comment]
@carpenike good idea!  The current helm repo address is https://billimek.com/billimek-charts/ which is being handled by github (the billimek.com DNS A record is pointing to github's servers (via the [apex domain configuration](https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain)) so in order to do this, the domain 'A' record will need to first be decoupled from github in order to set-up an external hosting solution to continue serving this helm repo as well as a proper redirect to the new helm repo.

At least, that's how I understand it would need to work.

**Comment by carpenike** [comment]
You're referring to the future phase / step? We can prove out that remote hosting feature will work with the k8s domain prior to notifying anyone of the change.

**Comment by billimek** [comment]
@DirtyCajunRice I think the steps you suggested are probably the best approach we can take.  With the way the currently helm repo URL (https://billimek.com/billimek-charts/) is configured, having it transparently work with a new home simply isn't doable.

Preserving commits is a nice touch instead of a net-new empty repo.

- [ ] create new repo in https://github.com/k8s-at-home/charts
- [ ] clone this repo to preserve git history and push directly as the new charts repo (https://github.com/k8s-at-home/charts)
- [ ] freeze contributions from non-maintainers (in both repos)
- [ ] 'transfer' all open issues to new repo
- [ ] Add the maintainers for group effort at updating all the different aspects on both repos
- [ ] create a branch in the old repo to stage full sweep deprecation in one MR
- [ ] Once new repo is satisfactorily ready/updated merge above branch in old repo
- [ ] Archive with established date on main readme saying it will be removed at x date
- [ ] unfreeze contributions from non-maintainers (in new repo)

What do you all think?

**Comment by onedr0p** [comment]
@billimek I think this is a great path forward. 

Would it be a good idea to have a `stable` directory and a `incubator` directory in the change-over. 
 This would allow us to test out charts before we move them to stable. For example rewrites of charts to statefulsets or other reasons...

**Comment by billimek** [comment]
Sadly, we [cannot transfer issues between organizations](https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository):

> You can only transfer issues between repositories owned by the same user or organization account.

**Comment by billimek** [comment]
Will handle the remaining **unifi** chart in the [new home](https://github.com/k8s-at-home/charts)

**Comment by CuBiC3D** [comment]
> Sadly, we [cannot transfer issues between organizations](https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository):
> 
> > You can only transfer issues between repositories owned by the same user or organization account.

What about bootstrapping the repository under your account, move the issues and then move the repository?

**Comment by billimek** [comment]
Ohh clever idea!

**Comment by billimek** [comment]
Deprecate chart checklist:

- [x] adguard-home
- [x] bazarr
- [x] bitwardenrs
- [x] blocky
- [x] calibre-web
- [x] comcast
- [x] couchpotato
- [x] deconz
- [x] digitalocean-dyndns
- [x] duplicati
- [x] esphome
- [x] frigate
- [x] grocy
- [x] heimdall
- [x] home-assistant
- [x] icantbelieveitsnotvaletudo
- [x] jackett
- [x] jellyfin
- [x] lazylibrarian
- [x] librespeed
- [x] lidarr
- [x] modem-stats
- [x] node-feature-discovery
- [x] node-red
- [x] nzbget
- [x] nzbhydra2
- [x] ombi
- [x] piaware
- [x] plex
- [x] powerdns
- [x] qbittorrent
- [x] radarr
- [x] rtorrent-flood
- [x] sabnzbd
- [x] ser2sock
- [x] sonarr
- [x] speedtest
- [x] speedtest-prometheus
- [x] tautulli
- [x] teslamate
- [x] unifi-poller
- [x] uptimerobot
- [x] uptimerobot-prometheus
- [x] xteve
- [x] zigbee2mqtt
- [x] zwave2mqtt

**Comment by billimek** [comment]
Will archive this repo on 2020-09-30
