### ISSUE TITLE
[home-assistant] Thoughts on adding dependent charts for DBs?

### ISSUE THREAD

**Issue by carpenike** [billimek/billimek-charts#318]
Any thoughts on adding an option for dependent charts (bitnami/postgres, bitnami/mariadb) into the chart.yaml? Would default to disabled for both but would remove the need for a second deployment.

**Comment by billimek** [comment]
@carpenike I was thinking about this too and think it's a good time to expand the chart to support something like this.  It's a good idea and I support it FWIW.

**Comment by billimek** [comment]
Fixed by #321
