### ISSUE TITLE
Adding new charts

### ISSUE THREAD

**Issue by WojoInc** [billimek/billimek-charts#324]
So I am in the process of wrapping up 2 charts that I'm building as part of my migration from Docker -> k8s:

- calibre-web
- lazylibrarian

It felt silly for me to stand up my own chart repo for what amounts to 2 charts at this point, especially given how similar they are to the charts for the other Linuxserver-based apps in this repo. Wondering if its okay to submit a PR to add them here? Also curious if there's a better place, given #317.

**Comment by bjw-s** [comment]
I've just created a PR for my LazyLibrarian chart. Maybe we could use this issue to discuss and align the two charts?

**Comment by billimek** [comment]
Go ahead and add them here for now.  Still trying to figure out the least-disruptive way to handle #317.

**Comment by billimek** [comment]
https://github.com/k8s-at-home/charts should be the new home for these charts.
