### ISSUE TITLE
decide what to do with kube-plex chart

### ISSUE THREAD

**Issue by billimek** [billimek/billimek-charts#83]
The kube-plex chart is hosted here because there is no chart registry currently hosting the excellent [kube-plex](https://github.com/munnerz/kube-plex/tree/master/charts/kube-plex) chart.

Currently it's a submodule and not really handled that great in this repo.

Personally speaking, using flux I can just reference the chart via git URL and don't _need_ it to be packaged int a chart repo.

I need to figure out a better way to host this, or convince upstream to host a chart registry instead.  That would be the better outcome.  There is [an existing issue](https://github.com/munnerz/kube-plex/issues/38) almost a year old attempting to support this.  Perhaps I can make the necessary changes as a PR (using github actions) to have munnerz package as a chart repo.

**Comment by cmacrae** [comment]
Hey @billimek :wave: I'm also of the opinion it'd be nice of this chart was available on a public Helm repository (as being discussed in some of the other issues). But I was wondering if you would mind sharing your Flux manifests you're using to deploy directly from the repo?  

I'm using Flux too and had been wondering how to approach this whilst the chart still just lives in a git

**Comment by billimek** [comment]
Hi @cmacrae, sure thing!  The flux HelmRelease I use for plex is [here](https://github.com/billimek/k8s-gitops/blob/master/default/plex/plex.yaml) as as well a separate set of plex chart values that get handled seperatley via a vault secrets operator [here](https://github.com/billimek/k8s-gitops/blob/master/default/plex/plex-helm-values.txt).

**Comment by cmacrae** [comment]
Wahoo! Thanks very much @billimek :pray: I'll take this for a spin this weekend :tada:

**Comment by billimek** [comment]
https://github.com/munnerz/kube-plex/pull/78 submitted to finally get kube-plex as a real-deal helm chart in the helm hub

**Comment by billimek** [comment]
Going to 'fork' and host the plex chart here until the [munnerz/kube-plex](https://github.com/munnerz/kube-plex) repo is once again active.

**Comment by onedr0p** [comment]
Sounds like a good idea, we can make improvements without the long wait time.
