### ISSUE TITLE
Update Nextcloud to 15?

### ISSUE THREAD

**Issue by doodlemania2** [billimek/billimek-charts#9]
I'm very new to Helm and charts but would love to deploy a Nextcloud 15. I see you are at 13. Would you be willing to update to 15 (or show me how?) :)

**Comment by billimek** [comment]
Hi @doodlemania2, I adopted the ['official' Nextcloud chart](https://github.com/helm/charts/tree/master/stable/nextcloud) over on the helm/charts repo which appears to be v15!
